### ISSUE TITLE
`mumbai` appears twice in deployments config

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher-contracts#88]
In `ape-config.yaml`:

```yaml
deployments:
  polygon:
    mumbai:
      ... 
  ethereum:
    ...
    mumbai:
      ...
```
It should only exist in `polygon` ecosystem
